---
server:
  host: 0.0.0.0
  port: 28420

motd: |
  hewwo :3

  This is the motd of the server. It supports
  multiple lines.  Yay!

default_channel: "#lobby"

redis:
  url: redis://127.0.0.1:6379/5
  # this will limit the amount of users being able to play on this server.
  # therefore: set it as high as possible
  pool: 1000
